// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH3vsB-tJmor86QTkwPm923Q2Yw65WmrE',
    appId: '1:561977644668:web:7d0a5d9732b9e1c7855bf9',
    messagingSenderId: '561977644668',
    projectId: 'khal24-potato-project',
    authDomain: 'khal24-potato-project.firebaseapp.com',
    storageBucket: 'khal24-potato-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMI0uGqD53xBusSFHdvH5seOx7PFm1nZc',
    appId: '1:561977644668:android:148ad1f86df39b2f855bf9',
    messagingSenderId: '561977644668',
    projectId: 'khal24-potato-project',
    storageBucket: 'khal24-potato-project.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXdkaXEQjaObeFI_2DsGfCIoyocymYL8o',
    appId: '1:561977644668:ios:5cd90f2516f7762e855bf9',
    messagingSenderId: '561977644668',
    projectId: 'khal24-potato-project',
    storageBucket: 'khal24-potato-project.firebasestorage.app',
    androidClientId: '561977644668-uh7ko88ud27kc5pvtq0rq4r5h16ik84g.apps.googleusercontent.com',
    iosClientId: '561977644668-9v30aptlmf1a7o5m5e72qrckgbtnga39.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXdkaXEQjaObeFI_2DsGfCIoyocymYL8o',
    appId: '1:561977644668:ios:5cd90f2516f7762e855bf9',
    messagingSenderId: '561977644668',
    projectId: 'khal24-potato-project',
    storageBucket: 'khal24-potato-project.firebasestorage.app',
    androidClientId: '561977644668-uh7ko88ud27kc5pvtq0rq4r5h16ik84g.apps.googleusercontent.com',
    iosClientId: '561977644668-9v30aptlmf1a7o5m5e72qrckgbtnga39.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH3vsB-tJmor86QTkwPm923Q2Yw65WmrE',
    appId: '1:561977644668:web:c0cb43c9b454e61a855bf9',
    messagingSenderId: '561977644668',
    projectId: 'khal24-potato-project',
    authDomain: 'khal24-potato-project.firebaseapp.com',
    storageBucket: 'khal24-potato-project.firebasestorage.app',
  );
}
