import 'package:flutter/material.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';

import 'app.dart';
import 'firebase_options.dart';
import 'providers/auth_provider.dart';
import 'providers/favorites_provider.dart';
import 'providers/recipes_provider.dart';
import 'providers/theme_provider.dart';
import 'providers/varieties_provider.dart';
import 'repositories/auth_repository.dart';
import 'repositories/favorite_repository.dart';
import 'repositories/recipe_repository.dart';
import 'repositories/variety_repository.dart';
import 'services/api_client.dart';
import 'services/auth_service.dart';
import 'services/favorite_service.dart';
import 'services/firebase_auth_service.dart';
import 'services/recipe_service.dart';
import 'services/variety_service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await EasyLocalization.ensureInitialized();

  // Firebase powers authentication. Config is generated by
  // `flutterfire configure` into firebase_options.dart (web + Android).
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // One shared HTTP client → one place for the token and error handling.
  final apiClient = ApiClient();

  runApp(
    EasyLocalization(
      supportedLocales: const [Locale('en'), Locale('ar')],
      path: 'assets/translations',
      fallbackLocale: const Locale('en'),
      child: MultiProvider(
        providers: [
          Provider<ApiClient>.value(value: apiClient),
          ChangeNotifierProvider(create: (_) => ThemeProvider()..load()),
          ChangeNotifierProvider(
            create: (_) => AuthProvider(
              FirebaseAuthService(),
              AuthRepository(AuthService(apiClient)),
              apiClient,
            ),
          ),
          ChangeNotifierProvider(
            create: (_) =>
                VarietiesProvider(VarietyRepository(VarietyService(apiClient))),
          ),
          ChangeNotifierProvider(
            create: (_) =>
                RecipesProvider(RecipeRepository(RecipeService(apiClient))),
          ),
          ChangeNotifierProvider(
            create: (_) =>
                FavoritesProvider(FavoriteRepository(FavoriteService(apiClient))),
          ),
        ],
        child: const MyApp(),
      ),
    ),
  );
}
